name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
- release
- qa

resources:
  repositories:
  - repository: KubernetesRepository
    endpoint: KubernetesReposGitServiceConnection-DartWing
    type: git
    name: Kubernetes/Kubernetes-Master
    ref: refs/heads/devtest
    trigger: none

  - repository: KubernetesRepositoryProd
    endpoint: KubernetesReposGitServiceConnection-DartWing
    type: git
    name: Kubernetes/Kubernetes-Master
    ref: refs/heads/prod
    trigger: none

stages:
- stage: BUILD
  jobs:
  - job: BuildJob
    pool:
      vmImage: ubuntu-24.04

    variables:
    - name: BuildConfiguration
      value: release
    - name: BuildPlatform
      value: 'any cpu'
    
    steps:

    - bash: |
        cat > $(build.artifactstagingdirectory)/Dockerfile <<EOF 
            FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
            WORKDIR /app
            EXPOSE 80 443
            
            FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
            ARG BUILD_CONFIGURATION=Release
            WORKDIR /src
            COPY ["DartWing.Web/DartWing.Web.csproj", "DartWing.Web/"]
            COPY ["DartWing.Frappe/DartWing.Frappe.csproj", "DartWing.Frappe/"]
            COPY ["DartWing.KeyCloak/DartWing.KeyCloak.csproj", "DartWing.KeyCloak/"]
            COPY ["DartWing.Google/DartWing.Google.csproj", "DartWing.Google/"]
            COPY ["DartWing.Microsoft/DartWing.Microsoft.csproj", "DartWing.Microsoft/"]
            RUN dotnet restore "DartWing.Web/DartWing.Web.csproj"
            COPY . .
            WORKDIR "/src/DartWing.Web"
            RUN dotnet build "DartWing.Web.csproj" -c \$BUILD_CONFIGURATION -o /app/build
            
            FROM build AS publish
            ARG BUILD_CONFIGURATION=Release
            RUN dotnet publish "DartWing.Web.csproj" -c \$BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
            
            FROM base AS final
            WORKDIR /app
            COPY --from=publish /app/publish .
            ENTRYPOINT ["dotnet", "DartWing.Web.dll"]
        EOF
      displayName: 'create DockerFile'
    

    - task: Docker@2
      displayName: 'buildAndPush image'
      inputs:
          ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
            containerRegistry: dotNetFarheapDockerRegistryProd
          ${{ else }}:
            containerRegistry: dotNetFarheapDockerRegistry
          repository: 'dartwing-dotnet_gatekeeper-$(Build.SourceBranchName)'
          Dockerfile: '$(build.artifactstagingdirectory)/Dockerfile'
          buildContext: 'src/DartWing'
          tags: |
            $(Build.BuildId)
            latest

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: DartWing-dotnet_gatekeeper'
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/'
          ArtifactName: 'dartwing-dotnet_gatekeeper'   

- stage: DEPLOY_QA
  displayName: DEPLOY QA
  dependsOn: BUILD
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'qa'))
  
  jobs:
  - job: Deploy
  
    steps:
    - checkout: KubernetesRepository

    - template: deploy.yml@KubernetesRepository
      parameters:
        deployAll: 'true'
        
        Project: dartwing
        ApplicationName: dotnet-gatekeeper
        ApplicationEnvironment: qa
        Namespace: dartwing
        certManager: true
        
        #ingress
        Hosts: 
          - dartwing-dotnet-gatekeeper-qa.tech-corps.com
        secretName: tech-corps-tls

        #deployment
        DeploymentID: $(Build.BuildId)
        CpuRequest: "0.05"
        CpuLimit: "0.40"
        MemoryRequest: "150Mi"
        MemoryLimit: "400Mi"
        Image: dotnetfarheapdockerregistry.azurecr.io/dartwing-dotnet_gatekeeper-$(Build.SourceBranchName):$(Build.BuildId)
        ImageRegistrySecret: dotnetfarheapdockerregistry
        Environments: 
          - name: ASPNETCORE_HTTP_PORTS
            value: 80
          - name: PapertrailSettings__HostName
            value: "dartwing-qa"
          - name: Microsoft__ClientId
            value: $(QA_MICROSOFT_CLIENTID)
          - name: Microsoft__ClientSecret
            value: $(QA_MICROSOFT_CLIENTSECRET)

- stage: DEPLOY_PROD
  displayName: DEPLOY PROD
  dependsOn: BUILD
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'release'))
  
  jobs:
  - job: Deploy
  
    steps:
    - checkout: KubernetesRepositoryProd

    - template: deploy.yml@KubernetesRepositoryProd
      parameters:
        deployAll: 'true'
        
        Project: dartwing
        ApplicationName: dotnet-gatekeeper
        ApplicationEnvironment: prod
        Namespace: dartwing
        certManager: true
        
        #ingress
        Hosts: 
          - dartwing-gatekeeper.opensoft.one
        secretName: dartwing-gatekeeper.opensoft.one-tls
        enableCors: 'true'
        corsAllowOrigin: 'https://witty-grass-08800361e.4.azurestaticapps.net,http://localhost:5173'

        #deployment
        DeploymentID: $(Build.BuildId)
        CpuRequest: "0.05"
        CpuLimit: "0.40"
        MemoryRequest: "150Mi"
        MemoryLimit: "400Mi"
        Image: dotnetfarheapdockerregistryprod.azurecr.io/dartwing-dotnet_gatekeeper-$(Build.SourceBranchName):$(Build.BuildId)
        ImageRegistrySecret: dotnetfarheapdockerregistryprod
        Environments: 
          - name: ASPNETCORE_HTTP_PORTS
            value: 80
          - name: PapertrailSettings__HostName
            value: "dartwing"     
          - name: Microsoft__ClientId
            value: $(PROD_MICROSOFT_CLIENTID)
          - name: Microsoft__ClientSecret
            value: $(PROD_MICROSOFT_CLIENTSECRET)
          - name: KeyCloak__Domain
            value: $(PROD_KEYCLOAK_DOMAIN)
          - name: KeyCloak__ClientId
            value: $(PROD_KEYCLOAK_CLIENTID)
          - name: KeyCloak__ClientSecret
            value: $(PROD_KEYCLOAK_CLIENTSECRET)
          - name: KeyCloak__RealmName
            value: $(PROD_KEYCLOAK_REALMNAME)
          - name: FrappeSite__BaseSiteHost
            value: $(PROD_FRAPPESITE_BASESITEHOST)   
          - name: ConnectionStrings__AzureStorage
            value: $(PROD_AZURESTORAGE_CONNECTIONSTRING)