name: ${COMPOSE_PROJECT_NAME:-gateway-project}
version: "3.7"
services:
    gateway:
        container_name: ${PROJECT_NAME:-gateway} # Name of the container
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            args:
                USERNAME: "${USER:-vscode}"       # Use host username, default to 'vscode'
                USER_UID: ${USER_UID:-1000}      # Use host UID, default to 1000
                USER_GID: ${USER_GID:-1000}      # Use host GID, default to 1000
                DEBUG: "${DEBUG:-false}"         # Default to 'false' if DEBUG is not set
        user: "${USER:-vscode}"                   # Run container as host user
        environment:
            - USER=${USER:-vscode}                # Make username available at runtime
            - USER_UID=${USER_UID:-1000}         # Make UID available at runtime
            - USER_GID=${USER_GID:-1000}         # Make GID available at runtime
            - DEBUG=${DEBUG:-false}              # Pass DEBUG to the container environment
        ports:
            - "0.0.0.0:5228:5228"
            - "0.0.0.0:7149:7149"
            - "0.0.0.0:1455:1455"
        networks:
            - dartnet
        volumes:
            # Workspace
            - ..:/workspaces/${PROJECT_NAME:-gateway}:cached

            # Git configuration
            - ~/.gitconfig:/home/${USER:-vscode}/.gitconfig:ro

networks:
  dartnet:
    driver: bridge
